version: '3.8'

services:
  php:
    build: .
    volumes:
      - .:/var/www/html
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "8083:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - php
    restart: unless-stopped
